name: Deploy to EC2

on:
  push:
    branches: 
     -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Clone or pull latest code
          if [ -d system-monitor ]; then
            cd system-monitor && git pull
          else
            git clone https://github.com/stealthcoderX/Desktop-System-Monitor.git system-monitor
            cd system-monitor
          fi

          # Build Docker image
          docker build -t system-monitor .

          # Stop and remove any running container
          docker rm -f system-monitor || true

          # Run container on port 80
          docker run -d --name system-monitor -p 80:5000 system-monitor
        EOF