name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Container to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/your-key.pem ubuntu@your-ec2-ip << 'EOF'
            docker rm -f system-monitor || true
            docker run -d --name system-monitor -p 80:5000 stealthcoderx/system-monitor:latest
          EOF